### ISSUE TITLE
Index name prefix problem in config.yml

### ISSUE THREAD

**Issue by lefakir** [algolia/AlgoliaSearchBundle#47]
I set up the bundle as mentionned in the documentation (Fill in your Algolia credentials) : 

```
# Algolia
algolia:
    catch_log_exceptions: true
    index_name_prefix: staging
```

And i get this error : 

```
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  Unrecognized option "index_name_prefix" under "algolia"
```
